## Copyright 2015-2016 Carnë Draug
## Copyright 2015-2016 Oliver Heimlich
## Copyright 2015-2019 Mike Miller
## Copyright 2024 John Donoghue
## Copyright 2025 Torsten Lilge
##
## Copying and distribution of this file, with or without modification,
## are permitted in any medium without royalty provided the copyright
## notice and this notice are preserved.  This file is offered as-is,
## without any warranty.

OCTAVE    ?= octave --silent
SED       := sed
MV        ?= mv -f
MAKEINFO  ?= makeinfo
# use --force in makeinfo since there are @refs to octave core functions
MAKEINFO_OPTIONS := --no-headers --no-split --no-validate \
												--set-customization-variable 'COPIABLE_LINKS 0'
# work out a possible help generator
ifeq ($(strip $(QHELPGENERATOR)),)
  ifneq ($(shell qhelpgenerator -v 2>/dev/null),)
    QHELPGENERATOR = qhelpgenerator
  else ifneq ($(shell qcollectiongenerator -v 2>/dev/null),)
    QHELPGENERATOR = qcollectiongenerator-qt5
  else ifneq ($(shell qcollectiongenerator -qt5 -v 2>/dev/null),)
    QHELPGENERATOR = qcollectiongenerator -qt5
  else
    QHELPGENERATOR = true
  endif
endif

DESCRIPTION := DESCRIPTION
PACKAGE := $(shell $(SED) -n -e 's/^[Nn]ame: *\(\w\+\)/\1/p' $(DESCRIPTION))
VERSION := $(shell $(SED) -n -e 's/^[Vv]ersion: *\(\w\+\)/\1/p' $(DESCRIPTION))
DATE    := $(shell $(SED) -n -e 's/^[Dd]ate: *\(\w\+\)/\1/p' $(DESCRIPTION))
DEPENDS := $(shell $(SED) -n -e 's/^[Dd]epends[^,]*, *\(.*\)/\1/p' $(DESCRIPTION) | $(SED) 's/ *([^()]*)//g; s/ *, */ /g')

TARGET_DIR      := target
RELEASE_DIR     := $(TARGET_DIR)/$(PACKAGE)-$(VERSION)
RELEASE_TARBALL := $(TARGET_DIR)/$(PACKAGE)-$(VERSION).tar.gz
DOCS_HTML_DIR   := docs
DOCS_DIR        := doc
DOCS_DEV_DIR    := devel/doc

SC_SMOD         := slicot-reference
SC_SRC          := src/slicot/src
SC_DOC          := doc/SLICOT

M_SOURCES       := $(wildcard inst/*.m)
CC_SOURCES      := $(wildcard src/*.cc)
TEXI_TMP        := $(DOCS_DEV_DIR)/functions.texi $(DOCS_DEV_DIR)/version.texi
DOCS_SOURCES    := $(DOCS_DEV_DIR)/$(PACKAGE).texi $(TEXI_TMP)
PKG_ADD         := $(shell grep -sPho '(?<=(//|\#\#) PKG_ADD: ).*' $(CC_SOURCES) $(M_SOURCES))

DOCS_PDF        := $(DOCS_DIR)/$(PACKAGE).pdf
DOCS_QCH        := $(DOCS_DIR)/$(PACKAGE).qch


.PHONY: help dist docs-html docs release install all check run clean

help:
	@echo " "
	@echo "Targets:"
	@echo " "
	@echo "   dist      - Create $(RELEASE_TARBALL) for release"
	@echo "   docs-html - Create html documentation in $(DOCS_DIR), assumes"
	@echo "               current version of $(PACKAGE) is installed;"
	@echo "   docs        Create the pdf manual and the Qt help file"
	@echo "               in $(DOC_DIR)"
	@echo "   qch       - Build Qt help file"
	@echo "   pdf       - Build pdf manual"
	@echo "   release   - Create dist, install and create docs,"
	@echo "               shows sha256sum of tarball"
	@echo
	@echo "   install   - Install the package in GNU Octave"
	@echo "   all       - Build all oct files"
	@echo "   check     - Execute package tests (with install)"
	@echo
	@echo "   clean     - Remove releases, doc and oct files"
	@echo "   distclean - Remove releases, oct files and compiled libraries"
	@echo " "

%.tar.gz: %
	@echo "Create $@ ..."
	@tar -c -f - --posix -C "$(TARGET_DIR)/" "$(notdir $<)" | gzip -9n > "$@"

# Create the directory structure of the destributed archive file.
# For this, archive the current git repo with some exceptions given
# in .gitattributes with export-ignore and untar it. Then, copy the
# slicot routines together with README and LICENSE file into a
# subdirectory. Finally move  TG04BX.f, a version of TB04BX.f extended
# for descriptor systems into that directory.
$(RELEASE_DIR): .git/index
	@echo "Creating package dist directory $@ ..."
	@-$(RM) -r $@
	@mkdir -p $@
	@echo "  git archive ..."
	@git archive -o $@/tmp.tar HEAD
	@cd $@ && tar -xf tmp.tar && $(RM) tmp.tar
	@echo "  copy pdf and qch file ..."
	@cp $(DOCS_PDF) $@/$(DOCS_DIR)/
	@cp $(DOCS_QCH) $@/$(DOCS_DIR)/
	@echo "  copy files from slicot ..."
	@mkdir -p $@/$(SC_SRC)
	@cp -t $@/$(SC_SRC) $(SC_SMOD)/src/*.f
	@cp -t $@/$(SC_SRC) $(SC_SMOD)/src_aux/*.f
	@cp $(SC_SMOD)/LICENSE   $@/$(SC_SRC)/../
	@cp $(SC_SMOD)/README.md $@/$(SC_SRC)/../README-SLICOT.md
	@cp $(SC_SMOD)/LICENSE   $@/$(SC_DOC)/
	@cp $(SC_SMOD)/README.md $@/$(SC_DOC)/README-SLICOT.md
	@echo "  bootstrap ..."
	@cd $@/src && ./bootstrap && $(RM) -r "autom4te.cache"
	@chmod -R a+rX,u+w,go-w "$@"

docs-html:
	@echo "Updating HTML documentation ... "
	@cd $(DOCS_DEV_DIR) && $(OCTAVE) --eval "docs_html (\"$(PACKAGE)\");"

$(DOCS_DEV_DIR)/version.texi: $(DESCRIPTION)
	@echo Generating $@ ...
	@echo "@c autogenerated from Makefile" > $@
	@echo "@set VERSION $(VERSION)" >> $@
	@echo "@set PACKAGE $(PACKAGE)" >> $@
	@echo "@set DATE $(DATE)" >> $@

# Collect all texinfo tests in one file. For being able to use
# makeinfo --pdf, --html and pdf-octave-doc and always have nice
# refs and links from @seealso commands in all output formats.
$(DOCS_DEV_DIR)/functions.texi: .git/index
	@echo Generating $@ \(collect all texinfo texts\) ...
	@$(DOCS_DEV_DIR)/mkfuncdocs.py --src-dir=inst/ --src-dir=src/ INDEX > $@
	@$(DOCS_DEV_DIR)/fix_seealso.pl $@

$(DOCS_PDF): $(DOCS_SOURCES)
	@echo Generating $@ ...
	@cd $(DOCS_DEV_DIR) && $(MAKEINFO) --pdf $(MAKEINFO_OPTIONS) $(PACKAGE).texi > /dev/null 2>&1
	@cd $(DOCS_DEV_DIR) && $(RM) *.out *.log *.idx *.ilg *.ind *.toc *.cp *.cps *.aux *.fn *.fns *.out
	$(MV) $(DOCS_DEV_DIR)/$(PACKAGE).pdf $(DOCS_PDF)

$(DOCS_QCH): $(DOCS_SOURCES)
	@echo Generating $@ ...
	@cd $(DOCS_DEV_DIR) && $(MAKEINFO) --html --css-ref=$(PACKAGE).css $(MAKEINFO_OPTIONS) $(PACKAGE).texi
ifeq ($(QHELPGENERATOR),true)
	$(warning No QHELPGENERATOR... skipping QT doc build)
else
	@cd $(DOCS_DEV_DIR) && ./mkqhcp.py $(PACKAGE)\
									&& $(QHELPGENERATOR) -s $(PACKAGE).qhcp -o $(PACKAGE).qhc > /dev/null 2>&1
	@cd $(DOCS_DEV_DIR) && $(RM) $(PACKAGE).qhcp $(PACKAGE).qhp $(PACKAGE).qhc $(PACKAGE).html
endif
	@$(MV) $(DOCS_DEV_DIR)/$(PACKAGE).qch $(DOCS_QCH)

qch: $(DOCS_QCH)

pdf: $(DOCS_PDF)

docs: qch pdf

dist: docs $(RELEASE_TARBALL)

release: dist install
	sha256sum $(RELEASE_TARBALL)
	@echo ''
	@echo '* Execute: git tag "control-${VERSION}"'
	@echo "* Push release branch to https://github.com/gnu-octave/pkg-control"
	@echo "* Push new tag to https://github.com/gnu-octave/pkg-control"
	@echo "* Create a new release on https://github.com/gnu-octave/pkg-control"
	@echo "* Update control.yaml in https://github.com/gnu-octave/packages"
	@echo "  and create/merge a pull request for the changes in this file"

install: dist $(RELEASE_TARBALL)
	@echo 'Installing package "${RELEASE_TARBALL}" locally ...'
	@$(OCTAVE) --eval 'pkg ("install", "${RELEASE_TARBALL}")'

all: $(CC_SOURCES)
	$(MAKE) -C src/ all

check: install
	$(OCTAVE) --path "inst/" --path "src/" \
	  --eval 'pkg test control'

clean:
	$(RM) -r $(TARGET_DIR)
	$(MAKE) -C src/ clean
	$(RM) $(DOCS_PDF) $(DOCS_QCH)
	$(RM) $(TEXI_TMP)

distclean: clean
	$(MAKE) -C src/ distclean
